### GENERAL SETTINGS ###

# Site settings
title: Chen Peng | 彭 宸
description: "Painter from Taiwan."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://chenpengstudio.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#000000" 
  primary_rgb: "0,0,0"
  secondary: "#52a53d" 
  secondary_rgb: "82,165,61" 
  link: "#222222"
  link_hover: "#999999"
  footer_heading: "#999999"
  footer_content: "#999999"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: envelope
    url: mailto:studiochenpeng@gmail.com
  - title: facebook
    url: https://www.facebook.com/jane.peng.507
  - title: instagram
    url: https://www.instagram.com/chennpenguinn

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
#address:
  #- lines:
    #- Cambridge, Massachusetts,
    #- United States.
email: studiochenpeng@gmail.com
#tel: 

### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png

# Short text about your company. 
about: "Chen received her BFA in Painting with an emphasis in Ceramics, from the
  Cleveland Institute of Art in 2016. Chen currently lives and works in Cambridge, MA."
